requires 'DBI';
requires 'DBD::Pg';
requires 'DBIx::Schema::DSL';
requires 'String::Random';
requires 'Git::Wrapper';
requires 'GitDDL::Migrator';
requires 'Term::UI';
requires 'Term::ReadLine';
requires 'Mojolicious::Plugin::CSRFDefender';
